baseURL = "https://dmytro.sh/"
languageCode = "en-us"
title = "Dmytro on Things"
theme = "kpumuk"
rssLimit = 20
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
ignoreFiles = [
  '\.excalidraw$',
  '/supplementary/',
  '/static/.*\.md',
  '/tools/',
  '/scripts/'
]

[permalinks]
posts = "/blog/:slug"

[params]
disableHLJS = true
repo = "https://github.com/kpumuk/blog-dmytro"
fontCSSURL = "https://use.typekit.net/fzy3wla.css"

[params.social]
twitter = "kpumuk"
github = "kpumuk"
mastodon = "@kpumuk@ruby.social"
linkedin = "kpumuk"
mail = "hi@dmytro.sh"
rss = true

[params.author]
name = "Dmytro Shteflyuk"
email = "hi@dmytro.sh"
bio = "Welcome to my corner of the Internet, where I write about things that interest me."

[markup]
defaultMarkdownHandler = "goldmark"

[markup.highlight]
noClasses = false
tabWidth = 4

[markup.goldmark.extensions.extras.superscript]
enable = true

[frontmatter]
# https://gohugo.io/getting-started/configuration/#configure-dates
date = ["publishDate", "date", "lastmod"]
publishDate = ["publishDate", "date", "lastmod"]
