baseURL = "https://dmytro.sh/"
languageCode = "en-us"
title = "Dmytro on Things"
theme = "kpumuk"
rssLimit = 20
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
ignoreFiles = [
  '\.excalidraw$',
  '/supplementary/',
  '/static/.*\.md',
  '/tools/',
  '/scripts/'
]

[author]
name = "Dmytro Shteflyuk"
email = "hi@dmytro.sh"

[permalinks]
posts = "/blog/:slug"

[params]
# social icons
twitter = "kpumuk"
github = "kpumuk"
mastodon = "@kpumuk@ruby.social"
mail = "hi@dmytro.sh"
rss = true
# home page profile
name = "Dmytro Shteflyuk"
bio = "Welcome to my corner of the Internet, where I write about things that interest me."
# misc
disableHLJS = true
repo = "https://github.com/kpumuk/blog-dmytro"
fontCSSURL = "https://use.typekit.net/fzy3wla.css"

[social]
twitter = "kpumuk"

[markup]

[markup.highlight]
noClasses = false
tabWidth = 4

[frontmatter]
# https://gohugo.io/getting-started/configuration/#configure-dates
date = ["publishDate", "date", "lastmod"]
publishDate = ["publishDate", "date", "lastmod"]
