baseURL = "https://dmytro.sh/"
languageCode = "en-us"
title = "Dmytro on Things"
theme = "kpumuk"
rssLimit = 20
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

[author]
name = "Dmytro Shteflyuk"
email = "hi@dmytro.sh"

[permalinks]
posts = "/blog/:slug"

[params]
# social icons
twitter = "kpumuk"
github = "kpumuk"
mastodon = "@kpumuk@ruby.social"
rss = true
# home page profile
name = "Dmytro Shteflyuk"
bio = "Welcome to my personal corner of Internet, where I write on things that interest me."
# misc
disableHLJS = true
repo = "https://github.com/kpumuk/blog-dmytro"
font_css_url = "https://use.typekit.net/fzy3wla.css"
